/** @format */

export enum AchievementType {
  MARKERS_CREATED = 'MARKERS_CREATED',
  MARKERS_COMPLETED = 'MARKERS_COMPLETED',
  MESSAGES_SENT = 'MESSAGES_SENT',
  REACTIONS_RECEIVED = 'REACTIONS_RECEIVED',
  HELP_PROVIDED = 'HELP_PROVIDED',
}
